{{- if ne .Values.accessToken "" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-rate-limit-exporter.serviceAccountName" . }}
  labels:
    {{- include "github-rate-limit-exporter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  ACCESS_TOKEN: {{ .Values.accessToken }}
{{- end }}
