{{- if .Values.serviceMonitor.create -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "github-rate-limit-exporter.fullname" . }}
  labels:
    {{- include "github-rate-limit-exporter.labels" . | nindent 4 }}
    release: prometheus-kube-prometheus-stack
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "github-rate-limit-exporter.fullname" . }}
  endpoints:
    - targetPort: http
{{- end }}
