name: Helm test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  helm-test:
    name: Helm test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.10.0"

      - name: Dry run
        run: |
          helm install --dry-run --debug github-rate-limit-exporter ./helm/github-rate-limit-exporter
          helm install --dry-run --debug github-rate-limit-exporter ./helm/github-rate-limit-exporter --set accessToken="testAccessToken"

      - name: Install github-rate-limit-exporter
        run: |
          helm install github-rate-limit-exporter ./helm/github-rate-limit-exporter
          
      - name: Check running
        run: |
          # hack
          sleep 15

          helm test github-rate-limit-exporter
  helm-servicemonitor-test:
    name: Helm ServiceMonitor test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.10.0"

      - name: Install Prometheus Operator
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack \
          --set alertmanager.enabled="false" \
          --set grafana.enabled="false" \
          --set kubeStateMetrics.enabled="false" \
          --set nodeExporter.enabled="false"

      - name: Dry run
        run: |
          helm install --dry-run --debug github-rate-limit-exporter ./helm/github-rate-limit-exporter --set serviceMonitor.create="true"

      - name: Install github-rate-limit-exporter
        run: |
          helm install github-rate-limit-exporter ./helm/github-rate-limit-exporter --set serviceMonitor.create="true"
          
      - name: Check running
        run: |
          # hack
          sleep 15

          helm test github-rate-limit-exporter

          # TODO: chack scraping by Prometheus