name: Helm test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  helm-test:
    name: Helm test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0

      - name: Dry run
        run: |
          helm install --dry-run --debug github-rate-limit-exporter ./helm/charts/github-rate-limit-exporter
          helm install --dry-run --debug github-rate-limit-exporter ./helm/charts/github-rate-limit-exporter --set accessToken="testAccessToken"

      - name: Install github-rate-limit-exporter
        run: |
          helm install github-rate-limit-exporter ./helm/charts/github-rate-limit-exporter
          
      - name: Check running
        run: |
          # hack
          sleep 15

          helm test github-rate-limit-exporter

  helm-servicemonitor-test:
    name: Helm ServiceMonitor test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0

      - name: Install Prometheus Operator
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack \
          --set alertmanager.enabled="false" \
          --set grafana.enabled="false" \
          --set kubeStateMetrics.enabled="false" \
          --set nodeExporter.enabled="false"

      - name: Dry run
        run: |
          helm install --dry-run --debug github-rate-limit-exporter ./helm/charts/github-rate-limit-exporter --set serviceMonitor.create="true"

      - name: Install github-rate-limit-exporter
        run: |
          helm install github-rate-limit-exporter ./helm/charts/github-rate-limit-exporter --set serviceMonitor.create="true"
          
      - name: Check running
        run: |
          # hack
          sleep 15

          helm test github-rate-limit-exporter

          # TODO: chack scraping by Prometheus

  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch main)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --target-branch main --debug

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --target-branch main --debug